name: Issue Completion

on:
  issues:
    types: [closed]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on issue
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueNumber = context.issue.number;
          github.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'イシューが完了しました！こちらの写真をご覧ください。![Image](https://drive.google.com/file/d/1YwObpePNubKe0XrOUnoBZ6wl4jtl14ST/view?usp=sharing)'
          })
